import "./page.module.css";
import { Inter } from "next/font/google";
import "./globals.css";
import FirstSetion from "./navbar/firstSetion";
import SecondSection from "./navbar/secondSection";
import ThirdSection from "./navbar/thirdSection";
import FourthSection from "./navbar/fourthSection";
import LeftSide from "./leftside/leftSide";
import Footer from "./footer/footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <FirstSetion />
          <SecondSection />
          <ThirdSection />
          <FourthSection />
          
        {children}

        <Footer/>
      </body>
    </html>
  );
}
